services:
  postgres:
    container_name: tsmono-postgres-dev
    image: postgres:17
    networks:
      - tsmono-network
    ports:
      - '${DB_PORT_EXTERNAL:-5432}:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-tsmono_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-tsmono_password}
      - POSTGRES_DB=${DB_NAME:-tsmono_db}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USER:-tsmono_user} -d ${DB_NAME:-tsmono_db}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    container_name: tsmono-redis-dev
    image: redis:8-alpine
    networks:
      - tsmono-network
    ports:
      - '${REDIS_PORT_EXTERNAL:-6379}:6379'
    volumes:
      - redis_data_dev:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  tsmono-network:
    driver: bridge
    name: tsmono-monorepo-network-dev

volumes:
  postgres_data_dev:
    name: tsmono_postgres_data_dev
  redis_data_dev:
    name: tsmono_redis_data_dev
