name: Shared CI

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'biome.json'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'biome.json'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/**'

jobs:
  shared:
    name: Shared
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build All
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test All
        run: pnpm test